name: build-test-deploy
on: push
jobs: 
  hello-world-job:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Say hello world!
        run: echo "$(cat hello_world.txt)"
        
  build:
    needs: hello-world-job
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: use node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: 安装npm
        run: npm install
      - name: 构建node.js
        run: npm run build
  test: 
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - name: checkout repo
        uses: actions/checkout@v3
      - name: use node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: 安装npm
        run: npm install
      - name: 构建node.js
        run: npm run build
      - name: 测试
        run: npm test
